# Generated by Django 4.2.7 on 2023-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillSpringApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='time',
            field=models.DateTimeField(default='11AM-2PM', max_length=30),
        ),
    ]
