# Generated by Django 4.2.7 on 2023-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillSpringApp', '0002_alter_products_phone_alter_products_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='course',
        ),
        migrations.RemoveField(
            model_name='products',
            name='email',
        ),
        migrations.RemoveField(
            model_name='products',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='products',
            name='time',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='Original Products'),
        ),
        migrations.AddField(
            model_name='products',
            name='origin',
            field=models.CharField(default='Kenya', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
