# Generated by Django 4.2.7 on 2023-11-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillSpringApp', '0004_rename_price_products_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
